org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20,1.21)

forge_version=47.4.10
forge_version_range=[47.0.0,48)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=xmly_endless_refined
mod_name=Endless Refined Integration
mod_version=1.0.0
mod_group_id=com.xmly.endlessrefined
mod_authors=xmlySUM

mod_license=LGPL-3.0
mod_description=Endless Inventory as inventory space, a diskless Refined Storage portable grid, and a multi-group hotbar.

jei_version=15.20.0.112

endless_inventory_version=1.1.2

refined_storage_version=1.12.4