@ParametersAreNonnullByDefault@MethodsReturnNonnullByDefault
package com.kwwsyk.endinv.common.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;