@ParametersAreNonnullByDefault@MethodsReturnNonnullByDefault
package com.kwwsyk.endinv.common.network.payloads;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;